### ISSUE TITLE
Landing mock up  figma

### ISSUE THREAD

**Issue by juandaveth** [EthereumBogota/meetdapp-frontend#4]
### Descripción de la tarea
Terminar en Figma el mock-up del landing page para su versión Desktop y Mobile

**To-do's Mockup Desktop**

- [x] Diseñar navbar
- [x] Diseñar sección Hero
- [x] Hacer sección con descripción del proyecto
- [x] Hacer sección de Q&A
- [x] Hacer footer

**To-do's Mockup Mobile**

- [x] Diseñar navbar
- [x] Diseñar sección Hero
- [x] Hacer sección con descripción del proyecto
- [x] Hacer sección de Q&A
- [x] Hacer footer
